# 以下为站点信息
site_name: 东北师大附中生存手册
site_url: https://ziyou-qinghua.github.io/

# 以下为仓库信息
repo_url: https://github.com/ziyou-qinghua/ziyou-qinghua.github.io/
repo_name: ziyou-qinghua/ziyou-qinghua.github.io/

# 以下为版权信息
copyright: '© 2024 <a href="https://github.com/ziyou-qinghua">Ziyou-qinghua Team</a>. Some rights reserved: <a rel="license" href="https://creativecommons.org/licenses/by-nc/3.0/">CC-BY-NC 3.0 License</a>. '

theme:
  language: zh
  name: material # 设定主题为 material
  custom_dir: overrides # 启用评论需要此行
  palette: #日夜模式切换
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple #基调色
      accent: green #强调色
      toggle:
        icon: material/weather-sunny
        name: 日间模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple #基调色
      accent: red #强调色
      toggle:
        icon: material/weather-night
        name: 夜间模式
  icon:
    repo: fontawesome/brands/github # 设置git仓库图标
  features:
    - content.code.copy # 启用代码块复制按钮，尽管我觉得用不上
    - navigation.tabs # 页顶导航栏
    - navigation.tabs.sticky # 粘性导航栏
    - toc.follow # 边栏自动滚动
    - navigation.top # 回到顶部
    - navigation.footer # 启用页尾上一页下一页按钮
    - navigation.instant # 内部链接即时加载

markdown_extensions: #markdown扩展插件
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

extra_javascript: #js文件
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

# 以下为目录信息
nav:
  - "index.md"
  - 前言:
      - "intro/docs.md"
      - "intro/notice.md"
      - "intro/contribution.md"
  - 日程安排:
      - "time/daily.md"
      - "time/break.md"
      - "time/lessons.md"
      - "time/entertainment.md"
  - 分班及班型:
      - "type/exam.md"
      - "type/num.md"
      - "type/gaokao.md"
  - 学校简介:
      - "school/uniform.md"
      - "school/ziyou.md"
      - "school/qinghua.md"
  # - 校外地图:
  - 硬件设备:
      - "device/classroom.md"
  - 学生团体:
      - "team/orgnization.md"
      - "team/club.md"
      - "team/unofficial.md"
  - 杂项:
      - "others.md"
  - "board.md"
